# Generated by Django 3.2.11 on 2022-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('D', 'deposits'), ('W', 'withdrawals')], max_length=200),
        ),
    ]
