# Generated by Django 3.2.11 on 2022-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=10),
        ),
    ]
