# Generated by Django 3.2.11 on 2022-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('S', 'Savings'), ('C', 'Credit')], default=None, max_length=10),
        ),
    ]
